verified-network-toolchain/petr4

lib/checker.ml
lib/checker.mli
lib/env.ml
lib/env.mli
lib/error.ml
lib/eval.ml
lib/parser.mly
lib/pretty.ml
lib/typed.ml
lib/types.ml
lib/types.mli

~~Only a few cases left for type equality.~~ Done!

Refactor typechecker

---

lib/pretty.ml
lib/types.ml
petr4.opam

* Fix bug in pretty printing for case of Expression.List
* Small fix for updating to Yojson 1.7.0

Two small bug fixes

---

lib/checker.ml
lib/lexer.mll
lib/parser.mly
lib/pretty.ml
lib/types.ml
lib/types.mli

* Abstract methods
* Intsance initializers

Add support for two experimental features in the parser and ASTs

---

lib/env.ml
lib/env.mli
lib/eval.ml
lib/target.ml
lib/target.mli

Adds new code for modifying bindings in an environment and uses them in `assign_lvalue`.

Fix issue 118

---

lib/env.ml
lib/eval.ml
lib/ops.ml
lib/p4core.ml
lib/prog.ml
lib/target.ml
triage/failures.csv

I think I fixed the VNull issue in #157 but most of the tests it broke are still failing. A lot of it looks like header union bugs so I am going to try to clean a few of them up in this PR.

Fix unions

---

lib/parser.mly

Allow empty statements in parsers

---

lib/checker.ml
lib/typed.ml
stf-test/custom-stf-tests/stack.p4

Call restrictions

---

lib/parser.mly

Fix bug in parser for annotations by merging adjacent tokens

---

deps/poulet4/lib/Semantics.v
deps/poulet4/lib/SyntaxUtil.v
deps/poulet4/lib/Target.v
deps/poulet4/lib/Tofino.v
deps/poulet4/lib/V1Model.v

This merge includes:
1. Instantiation for code with abstract methods, i.e. creating internal and extern environments for such code.
2. Simpl semantics for Tofino extern objects, in particular register action, which uses abstract methods.

Abstract method semantics

---

deps/poulet4/lib/P4cub/Transformations/Lifting/Lifted.v

Some of my Ltac is a little weird compared to the rest of the stuff in the file but I proved the last little bit of the theorem.

Prove that Statementize results in a Lifted ast

---

deps/poulet4/lib/P4Arith.v
deps/poulet4/lib/Semantics.v

Improve semantics for header and header union

---

.github/scripts/build-petr4-macos.sh
.github/scripts/build-petr4-ubuntu.sh
.github/scripts/typecheck-petr4-vs-p4c.sh
.github/workflows/build-petr4.yml
.github/workflows/ci-typechecker.yml
.github/workflows/push-petr4-docker-img.yml
Dockerfile

* build-petr4 is fixed (menhir version is fixed to a previous one that works correctly)
* push docker image is added. It requires us to have a docker account with a petr4 repo and we should add the username and password as secrets.
* ci-typecheck is added but it is not complete yet.

actions added/fixed

---

deps/poulet4/lib/Environment/Environment.v
deps/poulet4/lib/Semantics.v
deps/poulet4/lib/Value.v

Fix issue 315

---

README.md

I think the scripts were updated but the README wasn't.

Poulet4 readme zlist URL fix

---

.github/scripts/build-poulet4-macos.sh
.github/scripts/build-poulet4-ubuntu.sh
.github/workflows/bld-poulet4.yml
.github/workflows/build-poulet4.yml
deps/poulet4/poulet4.opam
petr4.opam

Fix Core dependency issue

---

deps/poulet4/lib/Ccomp/CCompEnv.v
deps/poulet4/lib/Ccomp/CCompSel.v
deps/poulet4/lib/P4cub/Semantics/Dynamic/BigStep/Value/Embed.v
deps/poulet4/lib/P4cub/Syntax/AST.v

Merging Natalie's embedding implementation into p4cub refactoring branch.

P4cub p4light 2.0

---

petr4.opam

Should fix the install issues @QinshiWang was having, I think. Thanks for catching this

Require Core v0.15 in petr4.opam

---

deps/poulet4/lib/Compile/ToP4cub.v
deps/poulet4/lib/GCL/GCL.v
deps/poulet4/lib/GCL/Inline.v
deps/poulet4/lib/GCL/TableInstr.v
deps/poulet4/lib/GCL/ToGCL.v
deps/poulet4/lib/GCL/V1model.v
deps/poulet4/lib/Monads/Result.v
deps/poulet4/lib/P4cub/Semantics/Dynamic/BigStep/Value/Embed.v
deps/poulet4/lib/P4light/Semantics/Interpreter.v
deps/poulet4/lib/P4light/Semantics/InterpreterSafe.v
deps/poulet4/lib/P4light/Semantics/Semantics.v
deps/poulet4/lib/P4light/Transformations/HoistNameless.v
deps/poulet4/lib/Utils/Util/ListUtil.v
lib/common.ml

Parametrize Result monad

---

.github/scripts/build-poulet4-macos.sh
.github/scripts/build-poulet4-ubuntu.sh

Updates the build scripts ran by the `build-poulet4` workflow to fix failing CI checks

Updated build scripts

---

deps/poulet4/lib/P4light/Semantics/Typing/IsTerm.v
deps/poulet4/lib/P4light/Semantics/Typing/Lemmas.v
deps/poulet4/lib/P4light/Semantics/Typing/LvalueTyping.v
deps/poulet4/lib/P4light/Semantics/Typing/Ok.v
deps/poulet4/lib/P4light/Semantics/Typing/Rules.v
deps/poulet4/lib/P4light/Semantics/Typing/Typing.v
deps/poulet4/lib/P4light/Semantics/Typing/Utility.v
deps/poulet4/lib/P4light/Semantics/Typing/ValueTyping.v
deps/poulet4/lib/P4light/Syntax/P4String.v
deps/poulet4/lib/Utils/AListUtil.v
deps/poulet4/lib/Utils/ForallMap.v
deps/poulet4/lib/Utils/Maps.v

typing rules for p4light update

Poulet4 p4light typing

---

coq/lib/P4light/Syntax/Value.v

Implements a more useful induction principle for `ValueSet`.

Induction Principle for ValueSet

---

coq/lib/Monads/Monad.v

Adds an infix operators for (applicative) functors

Functor Notations

---

coq/lib/Monads/Monad.v
coq/lib/P4cub/Semantics/Dynamic/BigStep/Value/Embed.v
coq/lib/Utils/AListUtil.v

Implements and verified projection of P4Light values. Depends on #421.

Value Projection

---

coq/lib/P4cub/Semantics/Dynamic/BigStep/Semantics.v
coq/lib/P4cub/Semantics/Dynamic/BigStep/Value/Embed.v

Implements and verified embedding of P4Light types into P4Cub types. I also modified the variable case of the type embedding relation to be simpler.

Type Embedding

---

coq/lib/P4cub/Semantics/Dynamic/BigStep/Interpreter.v

Implements and verifies the soundness of an interpreter for toplevel P4cub declarations. Now, all that remains to complete the P4cub interpreter is to write the interpreter for modules and programs. However, the module semantics seemed to be stubbed in as an empty relation.

Top Declaration Interpreter

---

coq/lib/Ccomp/CCompSel.v
coq/lib/Ccomp/Helloworld.v
coq/lib/Compile/ToP4cub.v
coq/lib/GCL/Inline.v
coq/lib/GCL/ToGCL.v
coq/lib/GCL/V1model.v
coq/lib/P4cub/Semantics/Climate.v
coq/lib/P4cub/Semantics/Dynamic/BigStep/InstUtil.v
coq/lib/P4cub/Semantics/Dynamic/BigStep/Interpreter.v
coq/lib/P4cub/Semantics/Dynamic/BigStep/Properties.v
coq/lib/P4cub/Semantics/Dynamic/BigStep/Semantics.v
coq/lib/P4cub/Semantics/Dynamic/BigStep/ValEnvUtil.v
coq/lib/P4cub/Semantics/Dynamic/BigStep/Value/Syntax.v
coq/lib/P4cub/Semantics/Dynamic/SmallStep/Util.v
coq/lib/P4cub/Semantics/Static/Auxiliary.v
coq/lib/P4cub/Semantics/Static/Typing.v
coq/lib/P4cub/Semantics/Static/Util.v
coq/lib/P4cub/Syntax/AST.v
coq/lib/P4cub/Syntax/Auxiliary.v
coq/lib/P4cub/Syntax/Shift.v
coq/lib/P4cub/Syntax/Substitution.v
coq/lib/P4cub/Transformations/Lifting/EvalSpec.v
coq/lib/P4cub/Transformations/Lifting/Lift.v
coq/lib/P4cub/Transformations/Lifting/Lifted.v
coq/lib/P4cub/Transformations/Lifting/Statementize.v
coq/lib/P4cub/Transformations/Lifting/TypingSpec.v
lib/compcertalize.ml
lib/p4cubSexp.ml
lib/printp4cub.ml

P4cub now separates `in` and `out` parameters/arguments into different lists.

Cub inout args

---

README.md

Minor changes to clarify the README.

Improving install instructions

---

coq/lib/P4cub/Transformations/Lifting/EvalSpec.v
coq/lib/P4cub/Transformations/Lifting/Lift.v
coq/lib/P4cub/Transformations/Lifting/TypingSpec.v
coq/lib/Utils/ProdN.v
dune-project
petr4.opam
poulet4.opam
poulet4_Ccomp.opam

Some automation does not work for Coq 8.16. I fixed one but still have to leave some manual proof. If any of you have time, we can have a Zoom meeting to discuss how to improve the current fix.
I only test the code on Coq 8.16.1. It may break on Coq 8.15.

Make the main branch compatible with Coq 8.16.1
