verified-network-toolchain/petr4

- lib/pretty.ml
Annotations were being printed in the wrong place.
> Fix pretty printing of annotations on table keys

- README.md
I haven't test run the installation instructions in a clean VM yet but I think they're right. We may also need to change the ocaml dependency in `petr4.opam` to require 4.06.
> Improve readme as suggested in #2

- examples/checker_tests/good/struct_init-1.p4
- lib/checker.ml
- lib/eval.ml
- lib/parser.mly
- lib/pretty.ml
- lib/types.ml
- lib/types.mli
* Add new case to `expression` production in `Parser`
* Add new construct to `Expression.t` in `Types`
* Add new case to `Pretty.Expression.format_t`
* Add stub in `Eval.eval_expression'` and helper function
`eval_struct`
* Add stub in `Checker.type_expression` and helper function
`type_struct_expr` (used a different name to avoid clash with
existing `type_struct`)
* Fixed example `struct_init-1.p4` to fit current P4 language definition
* Also changed parser so that productions are
```
r:
| something { }
| something else { }
```
instead of
```
r
: something { }
| something else { }
```
This makes it easier to search for specific productions.
> Add front-end support for struct initializers

- examples/checker_tests/good/issue1208-1.p4
- lib/common.ml
- lib/error.ml
- lib/types.ml
- test/dune
- test/test.ml
* Add `examples` as a Dune dependency
* Remove commands to change directories in `Test`
* Add `example_path` helper function to construct paths
* Add exception handling to avoid voluminous printouts on failed typechecking tests.
* Fix bad reference to `psa.p4` in `issue1208-1.p4`
> Fixup tests

- lib/parser.mly
Use our standard helper functions for parsing lists rather than a custom production for `realTypeArgList`
> Streamline realTypeArgList in parser

- examples/checker_tests/good/issue1717.p4
- lib/checker.ml
- lib/typed.ml
This will close #72. I have unary ops and binary ops working but I need to finish with
> Finish compile time evaluation (without instantiations)

- lib/checker.ml
- triage/failures.csv
I tried to fix constsigned.p4 but it turns out it requires evaluating casts at compile time, which seems like a separate diff. This made a few tests start passing. Closes #123.
> Allow bitslice of int

- lib/p4core.ml
- lib/target.ml
- lib/v1model.ml
- triage/failures.csv
Implemented externs hash, verify_checksum[_with_payload], and update_checksum[_with_payload]. Implemented hashing algorithms identity and random with the rest stubbed out. Looking for a sanity check on my mental model for how targets do hashing.
Note: it will not appear in the diff, but the implementation of 'eval_hash` starting on line 274 is part of this PR - I accidentally pushed the first commit to master.
> Hashing externs

- stf-test/custom-stf-tests/scope.p4
- stf-test/custom-stf-tests/scope.stf
- stf-test/test.ml
- test/test.ml
* The Alcotest predicate `packet_equal` was only checking the output port not the packet
* The STF test harness was confusingly inconsistent in how it represented port-packet pairs. We rationalized it to be (port,packet).
* Note: the STF test harness hides compilation errors -- it maps them to the empty list of packets, which could lead to bugs.
* And just to cap it all off, we currently implement dynamic scope :-/
> Fix STF tests

- lib/checker.ml
- lib/ops.ml
- test/test.ml
I redid the typechecker to insert implicit casts into the emitted AST. This branch passes all the tests that the master branch currently passes, but it doesn't make any new tests pass. This could be because things were flagged unsupported and removed from the test suite, I'm not sure. I want to take a look at that before merging.
> Implicit casts

- .travis.yml
This adds a `.travis.yml` file that sets up an Ubuntu VM with OCaml and runs the `ci-test` target.
Ubuntu does not ship with a recent version of OCaml, so the setup pulls in the latest version from Debian Sid.
> Travis build configuration.

- Makefile
- deps/Makefile
- deps/poulet4/.gitignore
- deps/poulet4/Makefile
- deps/poulet4/_CoqProject
- deps/poulet4/extraction/Extract.v
- deps/poulet4/extraction/Makefile
- deps/poulet4/extraction/dune-project
- deps/poulet4/extraction/lib/dune
- deps/poulet4/extraction/poulet4.opam
- deps/poulet4/lib/Environment.v
- deps/poulet4/lib/Eval.v
- deps/poulet4/lib/Monads/Monad.v
- deps/poulet4/lib/Monads/Option.v
- deps/poulet4/lib/Monads/State.v
- deps/poulet4/lib/Platform/Packet.v
- deps/poulet4/lib/Step.v
- deps/poulet4/lib/Syntax.v
- deps/poulet4/lib/Unpack.v
- deps/poulet4/lib/Utils.v
- deps/poulet4/lib/Value.v
This merges the work on Poulet4, the Coq formalisation of P4 semantics, into this repository in a way that preserves the commit history of the `cornell-netlab/poulet4` repo. 
The build is set up to compile the Coq development, extract it into OCaml, build that as an OPAM package and then have the main Petr4 build use that package. Bear in mind that the integration is still very much proof of concept at this stage; the only exported type is `Direction`.
I am not at all experienced in build systems for OCaml, so if there is a more idiomatic way to do this integration, please let me know.
> Use poulet4

- examples/checker_tests/good/recursive_extern.p4
- lib/checker.ml
- lib/prog.ml
- lib/typed.ml
This pull request changes externs to be nominal so that we can allow recursive extern types for free. The main code changes are replacing the extern type with a simple `Extern {name}` type and pushing the types of methods into their own spot in the typechecker environment.
I'm not crazy about the setup of types. If an extern is generic, an instance has type  `SpecializedType {base = Extern {name}; args = targs}` (read as `(extern name)<targs>`). A lot of the code assumes that types in canonical form do not have a type application constructor, so I wrote some ugly workarounds to get this working. I'm going to see if I can push the type arguments into the Extern constructor before this gets merged, but I wanted to open a PR since this solution does pass all the tests.
> Nominal externs

- deps/poulet4/lib/Ccomp/CCompSel.v
- deps/poulet4/lib/P4cub/Transformations/Lifting/Statementize.v
I could be wrong here but I think the statementize pass doesn't need to verify that constructor arguments are const. If it's being fed garbage (a program with non-const constructor arguments) it's okay for it to produce garbage (a program with side effects in a constructor argument list).
It should be a typechecker invariant that we can enforce separately.
> Don't check whether constructor args are const in statementize pass

- deps/poulet4/lib/LightExamples/MultiProtocol.v
- deps/poulet4/lib/P4cub/ToGCLTest.v
- deps/poulet4/lib/P4cub/Util/ListUtil.v
- deps/poulet4/lib/ToP4cub.v
- deps/poulet4/lib/ToP4cubTest.v
Add Switch-Statement processing to the P4light -> P4cub compiler.
Since p4cub doesn't have switch statements this means that we have to replace them with if-then-elses. The code uses a continuation to build up the ifs.
Summary of changes:
- add Multiprotocol.v test case 
- Eliminate switch statements in the ToP4cub compiler
- Add `findi` to `ListUtils`, which finds the optionally finds the the index of an element if its in the list (returning `None` if it doesn't exist)
> Switch Statements

- deps/poulet4/lib/LightExamples/MultiProtocol.v
- deps/poulet4/lib/P4cub/ToGCLTest.v
- deps/poulet4/lib/P4cub/Util/ListUtil.v
- deps/poulet4/lib/ToP4cub.v
- deps/poulet4/lib/ToP4cubTest.v
Reconcile conflicts between #290 and #286 that broke `poulet4`, necessitating #292.
Essentially #286 removed `BareNames` in some places that cause `MultiProtocol.v` not to build.
They've been fixed, and it builds for me now.
> Properly Merge Switch Statements

- .github/workflows/build-poulet4.yml
This PR adds the build-poulet4 workflow which runs on push or PR on the poulet4 branch.
Note, you need to have this workflow in the poulet4 branch to run it manually.
> build-poulet4 workflow added

- deps/poulet4/extraction/Extract.v
- deps/poulet4/extraction/dune
- deps/poulet4/lib/GenLoc.v
- deps/poulet4/lib/Monads/Error.v
- deps/poulet4/lib/Monads/Hoare/SP.v
- deps/poulet4/lib/Monads/Hoare/WP.v
- deps/poulet4/lib/Monads/Monad.v
- deps/poulet4/lib/Monads/Option.v
- deps/poulet4/lib/Monads/State.v
- deps/poulet4/lib/P4automata/GeneralBisim.v
- deps/poulet4/lib/SimplExpr.v
- deps/poulet4/lib/ToP4cub.v
- deps/poulet4_Ccomp/_CoqProject
- deps/poulet4_Ccomp/lib/Extract.v
Resolved or suppressed warnings relating to extraction:
- `nat` uses `Stdlib` instead of `Pervasives`, b/c [this pull-request is still unresolved](https://github.com/coq/coq/pull/15333).
- Added locality and database info to hints.
- Suppressed "ignored arguments" warning `20`.
> Poulet4 extraction warnings

- deps/poulet4/lib/Interpreter.v
- deps/poulet4/lib/InterpreterSafe.v
- deps/poulet4/lib/Semantics.v
- deps/poulet4/lib/Value.v
- deps/poulet4/lib/ValueUtil.v
Cleaner lvalues.
- `ValueLvalue` is no longer a mutually `Inductive` data type.
- `ValueLvalue` no longer has type annotations & thus no longer depends on `tags_t`.
- `ValLeftName` only has a locator now.
- `exec_read_array_access` uses the first header as the default value instead of generating one from a type annotation.
- Analogous updates to `Interpreter.v`.
The build seems to work on my machine.
> Poulet4 lvalue

- deps/poulet4_Ccomp/extraction/CompcertCaml/PrintCsyntax.ml
- deps/poulet4_Ccomp/lib/Extract.v
The name_of_ident function is relocated in Compcert 3.10. Also, I'm not sure if I should open a pull request for this kind of small changes, but I opened it anyway just for safety.
> fixed printing clight identifiers.

- lib/common.ml
- lib/p4cubSexp.ml
- lib/p4cubSexp.mli
Implements s-expression serialization for P4cub similar to how `ppx_sexp_conv` would--let me know if you have any comments about the grammar. In the future, it might be useful to add a parser for deserialization. If we did this, we could use qcheck to generate random tests asserting serialization and deserialization is an involution.
> P4cub S-expressions

- coq/lib/Monads/Monad.v
- coq/lib/P4cub/Semantics/Dynamic/BigStep/Semantics.v
- coq/lib/P4cub/Semantics/Dynamic/BigStep/Value/Embed.v
- coq/lib/P4light/Architecture/Target.v
- coq/lib/P4light/Architecture/V1ModelTarget.v
- coq/lib/P4light/Semantics/Interpreter.v
- coq/lib/P4light/Semantics/InterpreterSafe.v
- coq/lib/P4light/Semantics/Ops.v
- coq/lib/P4light/Semantics/Semantics.v
- coq/lib/P4light/Syntax/Value.v
Proposed changes
- Remove P4light's `Match` from `ValueSet`.
- Replace `Match` with `ValueSet` in `Target.v`
Questions:
1. In `ValSetValueSet` what is is the purpose of the members list? It was a list of list of `Match` but this has been replaced with `ValueSet`.
2. In `Semantics.v` `unwrap_table_entry` was used in `load_decl` to map a `TableEntry` to a `table_entry` and put it in a `genv`. Now the `Match`s in a `TableEntry` need to be converted to `ValueSet` which requires a relation. Perhaps should `TableEntry` be used in place of `table_entry` in `FTable`, so matches in tables are evaluated upon table invocation? Or maybe `load_decl` needs to be a relation too...
> no match in valset

- lib/context.ml
- lib/context.mli
- lib/lexer.mll
- lib/p4parser.mly
- lib/surface.ml
- lib/surface.mli
- test/test.ml
- triage/failures.csv
The precedences of < as a binary operator and < as the left side of a type argument list e.g. extern_fun<bool>(...) have to be different. This PR adds a new token L_ANGLE_ARGS for the case where < is the start of a type argument list and uses a lexer hack to distinguish them based on the trick used in p4c's lexer.
This fixes #69
> Lexer hack for precedence of type argument lists

- coq/lib/P4cub/Semantics/Dynamic/BigStep/Interpreter.v
- coq/lib/P4cub/Semantics/Dynamic/BigStep/Value/Auxiliary.v
- coq/lib/P4light/Semantics/Typing/Lemmas.v
- coq/lib/P4light/Semantics/Typing/Rules.v
- coq/lib/P4light/Semantics/Typing/Utility.v
- coq/lib/Utils/Util/FunUtil.v
Adds more notations for option tactics and uses them in different interpreter soundness proofs.
> Option Tactic Notations

- coq/lib/Ccomp/CCompSel.v
- coq/lib/Compile/ToP4cub.v
- coq/lib/GCL/GCL.v
- coq/lib/GCL/Inline.v
- coq/lib/GCL/ToGCL.v
- coq/lib/P4cub/Semantics/Dynamic/BigStep/ExprUtil.v
- coq/lib/P4cub/Semantics/Dynamic/BigStep/Properties.v
- coq/lib/P4cub/Semantics/Dynamic/BigStep/Semantics.v
- coq/lib/P4cub/Semantics/Dynamic/SmallStep/Util.v
- coq/lib/P4cub/Semantics/Static/Typing.v
- coq/lib/P4cub/Semantics/Static/Util.v
- coq/lib/P4cub/Syntax/AST.v
- coq/lib/P4cub/Syntax/Equality.v
- coq/lib/P4cub/Syntax/HeaderStack.v
- coq/lib/P4cub/Syntax/InferMemberTypes.v
- coq/lib/P4cub/Syntax/Shift.v
- coq/lib/P4cub/Syntax/Substitution.v
- coq/lib/P4cub/Transformations/Lifting/EvalSpec.v
- coq/lib/P4cub/Transformations/Lifting/Lift.v
- coq/lib/P4cub/Transformations/Lifting/Lifted.v
- coq/lib/P4cub/Transformations/Lifting/Statementize.v
- lib/compcertalize.ml
- lib/p4cubSexp.ml
- lib/printp4cub.ml
P4cub changed `SetValid` from a unary operation to a statement.
Adjustments were made in the `GCL` library to get petr4 to build that probably are not correct so @ericthewry feel free to make changes and corrections.
> SetValid is now a statement in cub

- coq/extraction/dune
- coq/lib/P4cub/Semantics/Dynamic/BigStep/Properties.v
- coq/lib/P4cub/Semantics/Static/Auxiliary.v
- coq/lib/P4cub/Syntax/Shift.v
- coq/lib/P4cub/Syntax/Substitution.v
- coq/lib/P4cub/Transformations/Lifting/EvalSpec.v
- coq/lib/P4cub/Transformations/Lifting/Lift.v
- coq/lib/P4cub/Transformations/Lifting/LiftList.v
- coq/lib/P4cub/Transformations/Lifting/LiftSpec.v
- coq/lib/P4cub/Transformations/Lifting/Lifted.v
- coq/lib/P4cub/Transformations/Lifting/Statementize.v
- coq/lib/P4cub/Transformations/Lifting/TypingSpec.v
- coq/lib/Utils/ForallMap.v
- coq/lib/Utils/ProdN.v
- coq/lib/Utils/Util/EquivUtil.v
- coq/lib/Utils/Util/FunUtil.v
- coq/lib/Utils/Util/ListUtil.v
- coq/lib/Utils/VecUtil.v
Shifting operations on P4cub terms during the lifting pass now share one definition and specification.
An arbitrary-length product type is the foundation of these changes.
> Streamline Shifting Boilerplate in P4cub Lifting Pass

- coq/lib/Compile/ToP4cub.v
This fixes an issue with the `SimplExpr` change in #427.
`IsValid` is now a function call that needs to be analyzed, not a member.
> isValid Bugfix

- dune-project
- petr4.opam
This PR constrains the installed version of Core to be v0.15. I think the fix for the Map issue is quick though.
Fixes #447.
> avoid Map incompatibility in core.v0.16.0
